# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Shows the shows the current user name
[username]
format = "[$user](bold yellow)"
show_always = true
disabled = false

# Shows the current host name
[hostname]
ssh_only = false
format = "@[$hostname](bold red) "
trim_at = ""
disabled = false

# Shows the current directory
[directory]
style = "cyan"
truncate_to_repo = true
truncation_length = 3
truncation_symbol = "../"
disabled = false

# Replace the "❯" symbol in the prompt with "✗" or "❯❯❯" or "×" or "λ" or "➜"
[character]
success_symbol = "[λ](bold white)"
error_symbol = "[λ](bold red)"
disabled = false

[aws]
symbol = " "
# format = 'via [$symbol]($style)'

[conda]
symbol = " "
# format = 'via [$symbol]($style)'

[dart]
symbol = " "
# format = 'via [$symbol]($style)'

[docker_context]
symbol = " "
# format = 'via [$symbol]($style)'

[elixir]
symbol = " "
# format = 'via [$symbol]($style)'

[elm]
symbol = " "
# format = 'via [$symbol]($style)'

[git_branch]
symbol = " "

[golang]
symbol = " "
# format = 'via [$symbol]($style)'

[hg_branch]
symbol = " "

[java]
symbol = " "
# format = 'via [$symbol]($style)'

[julia]
symbol = " "
# format = 'via [$symbol]($style)'

[nim]
symbol = " "
# format = 'via [$symbol]($style)'

[nix_shell]
symbol = " "
# format = 'via [$symbol]($style)'

[nodejs]
symbol = " "
# format = 'via [$symbol]($style)'

[package]
symbol = " "
# format = 'via [$symbol]($style)'

[perl]
symbol = " "
# format = 'via [$symbol]($style)'

[php]
symbol = " "
# format = 'via [$symbol]($style)'

[python]
symbol = " "
# format = 'via [$symbol]($style)'

[ruby]
symbol = " "
# format = 'via [$symbol]($style)'

[rust]
symbol = " "
# format = 'via [$symbol]($style)'

[swift]
symbol = "ﯣ "
# format = 'via [$symbol]($style)'

[lua]
symbol = " "
# format = 'via [$symbol]($style)'

[c]
symbol = " "
format = 'via [$symbol]($style)'
